### ISSUE TITLE
Create build pipeline

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/zowe-cli-mq-plugin#1]
What's the best way to create a build pipeline. I have included a Jenkinsfile with the source but it will not work as it is currently since it references integration and system tests which need running locally with a full MQ installation. 

So only the npm run test:unit or simply npm run test which calls test:unit would need to be invoked

**Comment by Colin-Stone** [comment]
@zFernand0 Should we set up using the pipeline or via the jenkins file?.

**Comment by zFernand0** [comment]
> @zFernand0 Should we set up using the pipeline or via the jenkins file?.

I believe there are quite a few things on that Jenkinsfile that could be removed since they are no longer used/available.

The integration test could be "updated" in order to run them inside the docker container spawned by Jenkins. For instance, you could install the CLI globally and then the plugin from source (i.e. `zowe plugins install .`) as part of a "setup-for-integration"-like stage.

As for system tests, we cannot run them as part of the pipeline since we've not gotten the proper infrastructure that allows the public to run them. 

Also, I'd recommend using the NodeJSPipeline library created for Zowe CLI for maintenance purposes. See [sample plugin Jenkinsfile](https://github.com/zowe/zowe-cli-sample-plugin/blob/master/Jenkinsfile)

**Comment by zFernand0** [comment]
We now have a GH Actions workflow for this
